name: Build, Test and Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  mark-success:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Create Success Artifact
      run: touch success.txt

    - name: Upload Success Artifact
      uses: actions/upload-artifact@v3
      with:
        name: success-marker
        path: success.txt

  check-success:
    needs: mark-success
    runs-on: ubuntu-latest

    steps:
    - name: Download Success Artifact
      uses: actions/download-artifact@v3
      with:
        name: success-marker

  nuget-build:
    needs: check-success
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        
    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build -c Release

    - name: Package
      run: dotnet pack --no-build -c Release

    - name: Push to NuGet
      run: dotnet nuget push "src/**/bin/Release/*.nupkg" -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
