name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack --no-build --configuration Release /p:PackageVersion=${{ github.run_number }}.0.0

      - name: Push
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: 'src/Source.csproj'
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          PACKAGE_NAME: 'Source'
